runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /(.*\.(gif|png|jpg|jpeg|svg|js|map|css|json|webmanifest))
  static_files: public/\1
  upload: public/(.*)
  secure: always

- url: (.*)
  static_files: public/index.html
  upload: public/index.html
  secure: always


