name: Build and Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: flock-community-website
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: gcloud app deploy
